-- MySQL Script generated by MySQL Workbench
-- čet 21 jan 2021 11:55:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dynamic_shop` ;
USE `dynamic_shop` ;

-- -----------------------------------------------------
-- Table `dynamic_shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_shop`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(1024) NOT NULL,
  `price_buy` DOUBLE UNSIGNED NULL,
  `price_sell` DOUBLE UNSIGNED NULL,
  `item_buys` INT NULL DEFAULT 0,
  `item_sells` INT NULL DEFAULT 0,
  `item_stock` INT NULL,
  `config_price_buy` DOUBLE UNSIGNED NULL,
  `config_price_sell` DOUBLE UNSIGNED NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_item_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `dynamic_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_shop`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NULL,
  `price_buy` DOUBLE NULL,
  `price_sell` DOUBLE NULL,
  `demand` DOUBLE NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
