-- MySQL Script generated by MySQL Workbench
-- čet 14 jan 2021 22:39:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dynamic_shop` DEFAULT CHARACTER SET utf8 ;
USE `dynamic_shop` ;

-- -----------------------------------------------------
-- Table `dynamic_shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_shop`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(1024) NOT NULL,
  `type` INT NOT NULL,
  `price_buy` DOUBLE NULL DEFAULT 0.00,
  `price_sell` DOUBLE NULL DEFAULT 0.00,
  `item_buys` INT NULL DEFAULT 0,
  `item_sells` INT NULL DEFAULT 0,
  `item_history` JSON NULL,
  `config_price_buy` DOUBLE NULL DEFAULT -1.00,
  `config_price_sell` DOUBLE NULL DEFAULT -1.00,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_item_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `dynamic_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
