-- MySQL Script generated by MySQL Workbench
-- tor 05 jan 2021 10:59:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dynamic_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dynamic_shop` DEFAULT CHARACTER SET utf8 ;
USE `dynamic_shop` ;

-- -----------------------------------------------------
-- Table `dynamic_shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_shop`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`item` (
  `id` INT NOT NULL,
  `material` VARCHAR(64) NOT NULL,
  `buy_price` DOUBLE NULL DEFAULT NULL,
  `sell_price` DOUBLE NULL DEFAULT NULL,
  `buys` INT NOT NULL DEFAULT 0,
  `sells` INT NOT NULL DEFAULT 0,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_item_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_item_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `dynamic_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_shop`.`item_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dynamic_shop`.`item_meta` (
  `id` INT NOT NULL,
  `display` VARCHAR(64) NULL DEFAULT '%item%',
  `lore` VARCHAR(512) NULL DEFAULT NULL,
  `priority` INT NULL DEFAULT 1000,
  `flatline` TINYINT NULL DEFAULT 0,
  `base64` VARCHAR(512) NULL DEFAULT NULL,
  `command` VARCHAR(256) NULL DEFAULT NULL,
  `item_id` INT NOT NULL,
  `item_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_meta_item1_idx` (`item_id` ASC, `item_category_id` ASC),
  CONSTRAINT `fk_item_meta_item1`
    FOREIGN KEY (`item_id` , `item_category_id`)
    REFERENCES `dynamic_shop`.`item` (`id` , `category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
