-- MySQL Script generated by MySQL Workbench
-- sob 02 jan 2021 11:09:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`item_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_meta` (
  `id` INT NOT NULL,
  `display` VARCHAR(64) NULL DEFAULT '%item%',
  `lore` VARCHAR(512) NULL DEFAULT NULL,
  `priority` INT NULL DEFAULT 1000,
  `flatline` TINYINT NULL DEFAULT 0,
  `base64` VARCHAR(512) NULL DEFAULT NULL,
  `command` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `id` INT NOT NULL,
  `material` VARCHAR(64) NOT NULL,
  `buy_price` DOUBLE NULL DEFAULT NULL,
  `sell_price` DOUBLE NULL DEFAULT NULL,
  `buys` INT NOT NULL DEFAULT 0,
  `sells` INT NOT NULL DEFAULT 0,
  `item_meta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_item_meta_idx` (`item_meta_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_item_meta`
    FOREIGN KEY (`item_meta_id`)
    REFERENCES `mydb`.`item_meta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
